cat > .github/workflows/ci.yml <<'YAML'
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        # lockfile がある前提で高速・再現性の高いインストール
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Run lint
        run: npm run lint --if-present

      - name: Run build
        run: npm run build
YAML
